=== vetmar81/PerformanceTracker/PerformanceTracker/PerfTracker/DbConfig.dtd
<!-- Database element and attributes-->
<!ELEMENT Database (TableMaps,FeatureCategories)>
<!ATTLIST Database name CDATA #REQUIRED>
<!ATTLIST Database server CDATA #REQUIRED>
<!ATTLIST Database user CDATA #REQUIRED>
<!ATTLIST Database password CDATA #IMPLIED>
<!ATTLIST Database port CDATA #IMPLIED>

<!-- TableMappings element -->
<!ELEMENT TableMaps (TableMap+)>

<!-- TableMapping element -->
<!ELEMENT TableMap (Member+)>
<!ATTLIST TableMap name CDATA #REQUIRED>
<!ATTLIST TableMap namespace CDATA #REQUIRED>
<!ATTLIST TableMap class CDATA #REQUIRED>
<!ATTLIST TableMap sequence CDATA #IMPLIED>

<!-- TableMapping element -->
<!ELEMENT Member EMPTY>
<!ATTLIST Member column CDATA #IMPLIED>
<!ATTLIST Member name CDATA #IMPLIED>
<!ATTLIST Member type CDATA #IMPLIED>
<!ATTLIST Member initiallyLoaded CDATA #IMPLIED>
<!ATTLIST Member isForeignKey CDATA #IMPLIED>

<!-- FeatureCategories element -->
<!ELEMENT FeatureCategories (FeatureCategory+)>

<!-- FeatureCategory element and attributes -->
<!ELEMENT FeatureCategory (SubCategory*)>
<!ATTLIST FeatureCategory id CDATA #REQUIRED>
<!ATTLIST FeatureCategory name CDATA #REQUIRED>

<!-- SubCategory element and attributes-->
<!ELEMENT SubCategory EMPTY>
<!ATTLIST SubCategory id CDATA #REQUIRED>
<!ATTLIST SubCategory name CDATA #REQUIRED>

=== vetmar81/PerformanceTracker/PerformanceTracker/PerfTracker/PgDbConfig.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Database SYSTEM "DbConfig.dtd">
<Database name="perftrack_dev" server="localhost" user="developer" password="developer" port="5432">
  <TableMaps>
    <TableMap name="po.player" namespace="Vema.PerfTracker.Database.Domain" class="Player" sequence="seq_player_id">
      <Member column="id" name="Id"/>
      <Member column="firstname" name="FirstName"/>
      <Member column="lastName" name="LastName" />
      <Member column="birthday" name="Birthday" />
      <Member column="country" name="Country"/>
      <Member name="dataHistory" type="PlayerDataHistory"/>
      <Member name="playerReference" type="PlayerReference"/>
    </TableMap>
    <TableMap name="po.team" namespace="Vema.PerfTracker.Database.Domain" class="Team" sequence="seq_team_id">
      <Member column="id" name="Id"/>
      <Member column="descriptor" name="Descriptor"/>
      <Member column="deleted" name="IsDeleted"/>
      <Member column="agegroup" name="AgeGroup"/>
      <Member name="playerReference" type="PlayerReference"/>
    </TableMap>
    <TableMap name="po.perfmeasurement" namespace="Vema.PerfTracker.Database.Domain" class="Measurement" sequence="seq_perfmeasurement_id">
      <Member column="id" name="Id"/>
      <Member column="playerreference_id" name="playerReference" type="PlayerReference" isForeignKey="true"/>
      <Member column="value" name="Value"/>
      <Member column="unit" name="Unit"/>
      <Member column="timestamp" name="TimeStamp"/>
      <Member column="perfsubfeature_id" name="subCategory" type="FeatureSubCategory" isForeignKey="true"/>
      <Member column="remark" name="Remark"/>
    </TableMap>
    <TableMap name="po.perffeaturecategory" namespace="Vema.PerfTracker.Database.Domain" class="FeatureCategory">
      <Member column="id" name="Id"/>
      <Member column="nicename" name="NiceName"/>
      <Member name="subCategories" type="FeatureSubCategory"/>
    </TableMap>
    <TableMap name="po.perfsubfeaturecategory" namespace="Vema.PerfTracker.Database.Domain" class="FeatureSubCategory">
      <Member column="id" name="Id"/>
      <Member column="featurecategory_id" name="category" type="FeatureCategory" isForeignKey="true"/>
      <Member column="nicename" name="NiceName"/>
    </TableMap>
    <TableMap name="ref.playerreference" namespace="Vema.PerfTracker.Database.Domain" class="PlayerReference" sequence="seq_playerreference_id">
      <Member column="id" name="Id"/>
      <Member column="player_id" name="player" type="Player" isForeignKey="true"/>
      <Member column="team_id" name="team" type="Team" isForeignKey="true"/>
      <Member name="measurements" type="Measurement"/>
      <Member column="validfrom" name="ValidFrom"/>
      <Member column="validto" name="ValidTo"/>
    </TableMap>
    <TableMap name="mt.playerdatahistory" namespace="Vema.PerfTracker.Database.Domain" class="PlayerDataHistory" sequence="seq_playerdatahistory_id">
      <Member column="id" name="Id"/>
      <Member column="player_id" name="player" type="Player" isForeignKey="true"/>
      <Member column="weight" name="Weight"/>
      <Member column="height" name="Height"/>
      <Member column="remark" name="Remark"/>
      <Member column="validfrom" name="ValidFrom"/>
      <Member column="validto" name="ValidTo"/>
    </TableMap>
  </TableMaps>
  <FeatureCategories>
    <FeatureCategory id="1" name="Ausdauer">
      <SubCategory id="1" name="Dauerlauf"/>
    </FeatureCategory>
  </FeatureCategories>
</Database>
